### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by jmalloc** [recoilphp/api#11]
Blocked by ~https://github.com/eloquent/phony/issues/250~

Edit: Phony now works with PHP 8, but the test/expectation frameworks used throughout Recoil projects don't. I am considering returning to PHPUnit since it's most likely to be maintained going forward.

**Comment by ezzatron** [comment]
@jmalloc Could you have a go with the `dev-php-8` version of Phony? I tried it myself, but there are other issues caused by the fact that [`match`](https://www.php.net/manual/en/control-structures.match.php) is now a keyword.

**Comment by jmalloc** [comment]
That error is actually from `peridot-php/leo`. At some point I'll need to invest in another test & assertion framework, but can you prepare releases over there still? If so I'll try to get a PR going when I get a chance.

**Comment by jmalloc** [comment]
I had a quick look at this. It's an easy fix for `leo` itself but there's further upstream problems beginning with `phpspec/prophecy` imported via `peridot-php/peridot-prophecy-plugin`.

It might be time to for me to switch testing & assertion frameworks but I'm not sure what to switch to. Kahlan was the one you suggested a while ago, but I don't think it's been updated with PHP 8 support yet either.

For many of these projects I could return to PHPUnit, but I had also added support for [running Recoil coroutines directly within Peridot tests](https://github.com/recoilphp/dev/tree/master/src/Peridot) so I'd want to provide an alternative to that too.

**Comment by ezzatron** [comment]
PHPUnit is almost certainly going to be first past the post with support for new PHP versions in future. Kind of a shame not to be able to use `describe` / `it` style though, of course. Kind of a surprise that Kahlan has no open issues for PHP 8 support either.

Whilst I still seem to have write access to the Peridot repos, there are new maintainers, and I haven't touched those repos in years. Might be time to just let it go.

**Comment by jmalloc** [comment]
Tag v1.0.2 opens the version constraint to allow PHP 8.

**Comment by ezzatron** [comment]
FWIW, Kahlan seemed to work fine under PHP 8 for me locally 🤷🏼‍♂️

**Comment by ezzatron** [comment]
Another option you might consider for converting the other test suites is https://pestphp.com/ - a describe/it runner based on PHPUnit that seems to have gained some traction. The PHPUnit version of Phony would probably "just work" I assume.
